DELETE FROM category;
INSERT INTO category (name, is_available) VALUES 
    ('Cancer Studies', true),
    ('Neuroscience', true),
    ('Infectious Diseases', true),
    ('Genetic Disorders', true),
    ('Cardiovascular Research', true),
    ('Mental Health', true),
    ('Public Health', true),
    ('Climate Change', true),
    ('Conservation Biology', true),
    ('Renewable Energy', true),
    ('Marine Biology', true),
    ('Ecology and Biodiversity', true),
    ('Sustainable Agriculture', true),
    ('Pollution and Waste Management', true),
    ('Artificial Intelligence', true),
    ('Robotics', true),
    ('Quantum Computing', true),
    ('Materials Science', true),
    ('Renewable Energy Technologies', true),
    ('Space Exploration', true),
    ('Nanotechnology', true),
    ('Economics and Development', true),
    ('Sociology', true),
    ('Psychology', true),
    ('Education Research', true),
    ('Political Science', true),
    ('Gender Studies', true),
    ('Anthropology', true),
    ('Particle Physics', true),
    ('Astrophysics', true),
    ('Theoretical Physics', true),
    ('Cosmology', true),
    ('Space Science', true),
    ('Quantum Mechanics', true),
    ('Genomics and Biotechnology', true),
    ('Microbiology', true),
    ('Evolutionary Biology', true),
    ('Botany', true),
    ('Zoology', true),
    ('Molecular Biology', true),
    ('Organic Chemistry', true),
    ('Inorganic Chemistry', true),
    ('Biochemistry', true),
    ('Physical Chemistry', true),
    ('Chemical Engineering', true),
    ('Environmental Chemistry', true),
    ('Data Science', true),
    ('Cryptography', true),
    ('Applied Mathematics', true),
    ('Machine Learning', true),
    ('Algorithms and Complexity Theory', true),
    ('Computational Biology', true),
    ('History', true),
    ('Philosophy', true),
    ('Linguistics', true),
    ('Cultural Studies', true),
    ('Art and Literature', true),
    ('Ethics in Science and Technology', true),
    ('Space Missions', true),
    ('Satellite Technology', true),
    ('Aerospace Engineering', true),
    ('Astronomy Research', true),
    ('Astrobiology', true),
    ('Agronomy', true),
    ('Food Security', true),
    ('Crop Science', true),
    ('Precision Agriculture', true),
    ('Livestock Research', true),
    ('Aquaculture', true),
    ('Nuclear Energy', true),
    ('Solar and Wind Energy', true),
    ('Energy Storage', true),
    ('Biofuels', true),
    ('Grid and Energy Systems', true),
    ('Environmental Policy', true),
    ('Health Policy', true),
    ('Science and Technology Policy', true),
    ('Education Policy', true),
    ('International Development', true),
    ('Civil Engineering', true),
    ('Mechanical Engineering', true),
    ('Electrical Engineering', true),
    ('Biomedical Engineering', true),
    ('Environmental Engineering', true),
    ('Bioethics', true),
    ('Data Privacy and Ethics', true),
    ('AI and Society', true),
    ('Global Health Ethics', true),
    ('Environmental Ethics', true),
    ('Cognitive Neuroscience', true),
    ('Brain-Computer Interfaces', true),
    ('Neurodegenerative Diseases', true),
    ('Memory and Learning', true),
    ('Sleep and Consciousness', true),
    ('Neuropsychology', true),
    ('Oceanography', true),
    ('Water Resource Management', true),
    ('Marine Conservation', true),
    ('Fisheries Science', true),
    ('Hydrology', true),
    ('Coral Reef Studies', true),
    ('Animal Health', true),
    ('Veterinary Medicine', true),
    ('Wildlife Medicine', true),
    ('Comparative Medicine', true),
    ('Animal Behavior', true),
    ('Earthquake and Tsunami Preparedness', true),
    ('Disaster Risk Reduction', true),
    ('Emergency Response Technology', true),
    ('Humanitarian Logistics', true),
    ('Urban Resilience', true),
    ('Gerontology', true),
    ('Aging and Cellular Research', true),
    ('Longevity Research', true),
    ('Age-related Diseases', true),
    ('Healthy Aging Interventions', true),
    ('Smart Cities', true),
    ('Transportation Systems', true),
    ('Urban Sustainability', true),
    ('Public Housing', true),
    ('Environmental Urban Planning', true),
    ('Child Psychology', true),
    ('Pediatric Healthcare', true),
    ('Early Childhood Development', true),
    ('Pediatric Nutrition', true),
    ('Child Behavior and Learning Disabilities', true),
    ('DNA Analysis', true),
    ('Crime Scene Investigation', true),
    ('Forensic Anthropology', true),
    ('Cyber Forensics', true),
    ('Toxicology and Drug Testing', true),
    ('Global Warming', true),
    ('Atmospheric Science', true),
    ('Climate Mitigation Strategies', true),
    ('Polar Research', true),
    ('Environmental Impact Studies', true),
    ('Human Performance', true),
    ('Exercise Physiology', true),
    ('Sports Medicine', true),
    ('Nutrition and Recovery', true),
    ('Injury Prevention', true),
    ('E-Learning', true),
    ('Educational Psychology', true),
    ('Virtual Classrooms', true),
    ('Learning Analytics', true),
    ('Special Education Research', true),
    ('Space Physiology', true),
    ('Effects of Microgravity', true),
    ('Life Support Systems', true),
    ('Vaccinology', true),
    ('Pathogen Research', true),
    ('Immunotherapy', true),
    ('Pandemic Preparedness', true),
    ('Antimicrobial Resistance', true),
    ('Archaeology', true),
    ('Museum Studies', true),
    ('Conservation of Artifacts', true),
    ('Cultural History', true),
    ('Digital Preservation', true),
    ('Bioplastics', true),
    ('Sustainable Textiles', true),
    ('Eco-Friendly Building Materials', true),
    ('Recycling Technologies', true),
    ('Circular Economy', true),
    ('Electric Vehicles', true),
    ('Autonomous Driving', true),
    ('Public Transit Systems', true),
    ('Sustainable Transportation', true),
    ('Urban Mobility Solutions', true),
    ('Gender and Society', true),
    ('Women in STEM', true),
    ('Gender Pay Gap Research', true),
    ('Equality in the Workplace', true),
    ('Social Justice', true),
    ('Human Trafficking', true),
    ('Refugee Studies', true),
    ('Humanitarian Law', true),
    ('Equality and Inclusion', true),
    ('Criminal Justice Reform', true),
    ('Community Policing', true),
    ('Drug Policy Research', true),
    ('Cybersecurity Research', true),
    ('Prison Reform', true),
    ('Depression and Anxiety Studies', true),
    ('Suicide Prevention', true),
    ('Post-Traumatic Stress Disorder (PTSD)', true),
    ('Mental Health in Adolescents', true),
    ('Workplace Mental Health', true),
    ('AI Safety and Governance', true),
    ('Decentralized Finance (DeFi)', true),
    ('Blockchain for Social Good', true),
    ('Smart Contracts and Governance', true),
    ('Blockchain in Healthcare', true),
    ('Decision Making', true),
    ('Behavioral Finance', true),
    ('Market Dynamics', true),
    ('Consumer Psychology', true),
    ('Incentives and Behavioral Change', true),
    ('Endangered Species Protection', true),
    ('Habitat Preservation', true),
    ('Conservation Technology', true),
    ('Biodiversity Research', true),
    ('Wildlife Corridors', true),
    ('Exoplanet Research', true),
    ('Gravitational Waves', true),
    ('Space Telescopes', true),
    ('Lunar and Mars Exploration', true),
    ('Solar System Studies', true)
